### ISSUE TITLE
Sphinx docs

### ISSUE THREAD

**Issue by moggers87** [moggers87/django-sendfile2#31]
The readme is a bit long IMO and setting up Sphinx as I have for exhibition and salmon shouldn't be too hard.

**Comment by sean0x42** [comment]
I think this project desperately needs some docs, or potentially even a clean up effort for the README. As someone new to the library, I found it quite difficult to figure everything out. 

One thing that should be addressed in the new docs/README: How do you actually configure which backend is used? The README doesn't make it clear whether to use a string e.g.

```python
SENDFILE_BACKEND = "sendfile.backend.nginx"
```
or to import some module...

```python
from django_sendfile import sendfile
SENDFILE_BACKEND = sendfile.backend.nginx
```

**Comment by sean0x42** [comment]
Could also update the README so that each backend is listed as a link, and not given an entire section. Clicking that link takes you to a page in the GitHub wiki which describes exactly how to get up and running with that specific backend.

**Comment by moggers87** [comment]
The README is quite bad, it's still pretty much in the same shape it was when I forked this project.

**Comment by sean0x42** [comment]
So which way would you rather go @moggers87 ? Clean up README + Sphinx docs or Clean up README + GitHub wiki. I would happily lend a hand with either.

**Comment by moggers87** [comment]
Basic docs have been added in 383be13d75c0b631c6aa0798b9b286d70b1ac1da

If there's anything missing, open a PR :wink:
