### ISSUE TITLE
Encoding of filename

### ISSUE THREAD

**Issue by srkunze** [moggers87/django-sendfile2#35]
Hi,

in recents versions, backends.xsendfile.sendfile does not encode the given filename anymore and passes on the Unicode str. That's an issue with special characters like `/home/user/test/äüö.pdf`.

```
 def sendfile(request, filename, **kwargs):
    filename = six.text_type(filename)
    if six.PY2:
        filename = filename.encode("utf-8")

    response = HttpResponse()
    response['X-Sendfile'] = filename

    return response
```

Would it be possible to remove that if-condition?

In case you wonder why we do not pass bytes to `sendfile.sendfile` in the first place:

`sendfile.sendfile` uses `guess_type(filename)`, which does not work with bytes.

**Comment by tidenhub** [comment]
It seems `filename = six.text_type(filename)` makes trouble cause the latest version works fine:
```
def sendfile(request, filename, **kwargs):
    filename = str(filename)
    response = HttpResponse()
    response['X-Sendfile'] = filename
```

**Comment by moggers87** [comment]
@srkunze can tell us which version you're using?

**Comment by tidenhub** [comment]
We are using 0.4.3, cause we are using it at a Py2 / Py3 System.

**Comment by moggers87** [comment]
I no longer support Python 2.

I suggest making a custom backend with whatever fixes you need and using that until you can migrate to a newer version of django-sendfile2
