### ISSUE TITLE
Allow passing django file objects to sendfile

### ISSUE THREAD

**Issue by sevdog** [moggers87/django-sendfile2#50]
It would be great if `sendfile` could support [`django.core.files.File`](https://docs.djangoproject.com/en/3.1/ref/files/file/#the-file-object) and [`django.db.models.fields.FileField`]( https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.fields.files.FieldFile) as an argument in place of `filename`.

This could improve usability, since many files are stored as filefield.

**Comment by moggers87** [comment]
That would only work if `FileSystemStorage` was being used as `FileField` doesn't store the MIME type, so we'd to inspect the file ourselves. The user could pass in a MIME type themselves, but that defeats the point of supporting `FileField` in the first place :smile_cat:

**Comment by sevdog** [comment]
I was not thinking about mime-type guessing, since that is not stored nor accessible via django file API.

I was thinking about a more user-friendly approach by using:

```python
sendfile(mymodel.file_field)
sendfile(myfile)
```

In place of the current:

```python
sendfile(mymodel.file_field.path)
sendfile(myfile.name)
```

Obviously to work with `FileField` (and derived fields) `field.storage` must implement the [`path` method](https://docs.djangoproject.com/en/3.1/ref/files/storage/#django.core.files.storage.Storage.path) or whatever method is required by sendfile and an `ImproperlyConfigured` error should be raised otherwise.

**Comment by moggers87** [comment]
I'm liking this idea less and less. Users are going to be confused and frustrated if we tell them we support `File` and `FileField` directly, only to find out we only support *one* storage backend.

Thanks for submitting this issue, but I don't think we'll be implementing this.
