### ISSUE TITLE
Using of deprecated function with Django4

### ISSUE THREAD

**Issue by Darbados** [moggers87/django-sendfile2#52]
Hellow, the following problem has been faced while migrating to Django 4

from django.utils.http import urlquote
ImportError: cannot import name 'urlquote' from 'django.utils.http'

**Comment by ad-m** [comment]
Could you provide PR to fix that (maybe add Django 4.0 to CI matrix too)?

**Comment by Darbados** [comment]
I would like to do it, but I don't see that breaking line of code within the latest **main** version. I see that you're using the aliases from urllib.parse according to the Django notes, so I guess that the current version is build by an older version of the repo?

**Comment by moggers87** [comment]
Yup, looks like I need to do another release :smile_cat:

I'll update the test matrix with Django 4.0 first and then if that goes well I'll do a release.

**Comment by moggers87** [comment]
New release: https://pypi.org/project/django-sendfile2/0.6.1/
