### ISSUE TITLE
[`Enchancement`] : Support caddy server

### ISSUE THREAD

**Issue by baseplate-admin** [moggers87/django-sendfile2#56]
Hi there,

Thanks for making this awesome project. Do you guys plan to have support for [`caddyserver`](https://caddyserver.com/)?

Here is a simple config to have caddy support X-Sendfile : 

```caddyfile
   handle /* {
        reverse_proxy localhost:8000 {
            @sendfile header X-Sendfile *
            handle_response @sendfile {
                rewrite {http.reverse_proxy.header.X-Sendfile}
                file_server
            }
        }
    }
 ````

**Comment by moggers87** [comment]
If caddy supports X-Sendfile then it should be good to go already.

**Comment by baseplate-admin** [comment]
Caddy by default doesn't have `X-Sendfile` directive.

From there [document](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy) they use `X-Accel-Redirect`
```caddyfile
reverse_proxy localhost:8080 {
	@accel header X-Accel-Redirect *
	handle_response @accel {
		root    * /path/to/private/files
		rewrite * {rp.header.X-Accel-Redirect}
		file_server
	}
}

```

Shouldn't there be a section in `README.md` clarifying this ?
