### ISSUE TITLE
wheel doesn't support Python 3.3 anymore

### ISSUE THREAD

**Issue by dgilge** [moggers87/django-sendfile2#6]
Looking into the Travis CI logs:

`wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6`

This is since version [0.30.0](https://github.com/pypa/wheel/blob/master/CHANGES.txt).

What do you prefer?

1. Remove Python 3.3 from tests or
2. tell Travis CI to use an older version of `wheel`?

**Comment by moggers87** [comment]
Dropping Python 3.3 is fine. You can add that as a separate commit to #5
