### ISSUE TITLE
Does sendfile need to be added to INSTALLED_APPS?

### ISSUE THREAD

**Issue by alexandresebrao** [moggers87/django-sendfile2#9]
I was having someproblems when setting the backend, because I thought it should be like that:
 SENDFILE_BACKEND = sendfile.backends.development

so I did like this. 
 SENDFILE_BACKEND = 'sendfile.backends.development'

But is not clear if I should put sendfile on installed_apps.

**Comment by moggers87** [comment]
As far as I know, there's no reason to put `sendfile` in `INSTALLED_APPS`. I'm not actually sure what would happen if you did, but I'd assume the answer to be "nothing".

**Comment by moggers87** [comment]
Finally got around to testing this - it appears to make no difference if `sendfile` is added to `INSTALL_APPS` or not.
